image: maxking/mailman-ci-runner

python2.7:
  script:
  - tox -e py27

python3.4:
  script:
  - tox -e py34

python3.5:
  script:
  - tox -e py35

python3.6:
  script:
  - tox -e py36

lint:
  script:
  - tox -e lint

docs:
  script:
  - tox -e docs
